---
--- Generated by Luanalysis
--- Created by yaofa.
--- DateTime: 2023/8/17 21:48
---

val =redis.call('get',KEYS[1])

if val==false then
    -- key 不存在
    return redis.call('set',KEYS[1],'EX',ARGV[1],ARGV[2])
elseif val==ARGV[1] then
    -- 你上次加锁成功
math
end
